[project]
name = "fastai"
version = "0.1.0"
description = "FastAI backend project."
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "editorconfig-checker==3.2.1",
    "fastapi[standard]==0.115.12",
    "ruff==0.11.13",
]
